[package]
name = "rayon-tracing"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rayon  = "1"
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["registry"] }
tracing-core = "0.1"
